{"name": "test_login_valid_credentials", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n\tGetHandleVerifier [0x0101FC03+61635]\n\tGetHandleVerifier [0x0101FC44+61700]\n\t(No symbol) [0x00E405D3]\n\t(No symbol) [0x00E8899E]\n\t(No symbol) [0x00E88D3B]\n\t(No symbol) [0x00ED0E12]\n\t(No symbol) [0x00EAD2E4]\n\t(No symbol) [0x00ECE61B]\n\t(No symbol) [0x00EAD096]\n\t(No symbol) [0x00E7C840]\n\t(No symbol) [0x00E7D6A4]\n\tGetHandleVerifier [0x012A4523+2701795]\n\tGetHandleVerifier [0x0129FCA6+2683238]\n\tGetHandleVerifier [0x012BA9EE+2793134]\n\tGetHandleVerifier [0x010368C5+155013]\n\tGetHandleVerifier [0x0103CFAD+181357]\n\tGetHandleVerifier [0x01027458+92440]\n\tGetHandleVerifier [0x01027600+92864]\n\tGetHandleVerifier [0x01011FF0+5296]\n\tBaseThreadInitThunk [0x76325D49+25]\n\tRtlInitializeExceptionChain [0x77C3D03B+107]\n\tRtlGetAppContainerNamedObjectPath [0x77C3CFC1+561]", "trace": "self = <test_login.TestLogin object at 0x0000027CAA267440>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"bfd753b5de5e5ae5295f370500cd5db4\")>\n\n    def test_login_valid_credentials(self, setup):\n        login_page = LoginPage(setup)\n        login_page.login(config.Config.LOGIN_USERNAME, config.Config.LOGIN_PASSWORD)\n>       assert \"Employee Profile\" in login_page.profile_title()\n\ntestcases\\test_login.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\login_page.py:24: in profile_title\n    return self.helpers.text(LOC.PROFILE_PAGE)\nutils\\helpers.py:37: in text\n    element = self.wait_for_element(locator, condition=\"visible\")\nutils\\helpers.py:21: in wait_for_element\n    return self.wait.until(EC.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"bfd753b5de5e5ae5295f370500cd5db4\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x0000027CA9F00040>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       \tGetHandleVerifier [0x0101FC03+61635]\nE       \tGetHandleVerifier [0x0101FC44+61700]\nE       \t(No symbol) [0x00E405D3]\nE       \t(No symbol) [0x00E8899E]\nE       \t(No symbol) [0x00E88D3B]\nE       \t(No symbol) [0x00ED0E12]\nE       \t(No symbol) [0x00EAD2E4]\nE       \t(No symbol) [0x00ECE61B]\nE       \t(No symbol) [0x00EAD096]\nE       \t(No symbol) [0x00E7C840]\nE       \t(No symbol) [0x00E7D6A4]\nE       \tGetHandleVerifier [0x012A4523+2701795]\nE       \tGetHandleVerifier [0x0129FCA6+2683238]\nE       \tGetHandleVerifier [0x012BA9EE+2793134]\nE       \tGetHandleVerifier [0x010368C5+155013]\nE       \tGetHandleVerifier [0x0103CFAD+181357]\nE       \tGetHandleVerifier [0x01027458+92440]\nE       \tGetHandleVerifier [0x01027600+92864]\nE       \tGetHandleVerifier [0x01011FF0+5296]\nE       \tBaseThreadInitThunk [0x76325D49+25]\nE       \tRtlInitializeExceptionChain [0x77C3D03B+107]\nE       \tRtlGetAppContainerNamedObjectPath [0x77C3CFC1+561]\n\nC:\\Users\\Sinergia\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "attachments": [{"name": "test_login_valid_credentials - FAILED - 20250522_201655", "source": "ef6c63c4-a381-4003-bbac-01e6644bacc1-attachment.png", "type": "image/png"}], "start": 1747925204616, "stop": 1747925215499, "uuid": "33b76f32-d84d-4028-8956-a60d31d6de5e", "historyId": "33b09052f0e2dc4c3195b94de833657f", "testCaseId": "33b09052f0e2dc4c3195b94de833657f", "fullName": "testcases.test_login.TestLogin#test_login_valid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-LIFTNJ8"}, {"name": "thread", "value": "23004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}